
------------TASK A------------

CREATE TABLE STUDENT(
	NAME VARCHAR2(20),
	ID NUMBER,
	CGPA NUMBER(3,2),
	CONSTRAINTS PK_STUDENT PRIMARY KEY(ID)
);

CREATE OR REPLACE TRIGGER INSERTION_PRINT_VALUES
AFTER INSERT ON STUDENT
FOR EACH ROW
	WHEN(NEW.ID > 0)
DECLARE
	ID_ NUMBER;
	NAME_ VARCHAR2(20);
	CGPA_ NUMBER(3,2);
BEGIN
	ID_ := :NEW.ID;
	NAME_ := :NEW.NAME;
	CGPA_ := :NEW.CGPA;
	
	DBMS_OUTPUT.PUT_LINE('####--NEW ROW DATA--####');
	DBMS_OUTPUT.PUT_LINE('ID   :: ' || ID_);
	DBMS_OUTPUT.PUT_LINE('NAME :: ' || NAME_);
	DBMS_OUTPUT.PUT_LINE('CGPA :: ' || CGPA_);
END;
/

CREATE SEQUENCE STUDENT_ID
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 20;

SET SERVEROUTPUT ON;
SET SERVEROUTPUT ON FORMAT WORD_WRAPPED;
SET ECHO ON;

INSERT INTO STUDENT(ID, NAME, CGPA) VALUES(STUDENT_ID.NEXTVAL,'AMADOU OLABI',3.5);
INSERT INTO STUDENT(ID, NAME, CGPA) VALUES(STUDENT_ID.NEXTVAL,'FOPA YUFFON',3.45);
INSERT INTO STUDENT(ID, NAME, CGPA) VALUES(STUDENT_ID.NEXTVAL,'ALY AKDER',4.0);
INSERT INTO STUDENT(ID, NAME, CGPA) VALUES(STUDENT_ID.NEXTVAL,'ABDEL KADER',3.92);
INSERT INTO STUDENT(ID, NAME, CGPA) VALUES(STUDENT_ID.NEXTVAL,'ABDEL KARIM',3.75);
INSERT INTO STUDENT(ID, NAME, CGPA) VALUES(STUDENT_ID.NEXTVAL,'TANI BARKAT',3.85);
INSERT INTO STUDENT(ID, NAME, CGPA) VALUES(STUDENT_ID.NEXTVAL,'ABDUL BAGUI',4.0);


-------------------TASK B-------------------------------

CREATE TABLE CITIZEN(
	ID VARCHAR2(20),
	NAME VARCHAR2(20),
	DV VARCHAR2(2),
	DateOfBirth DATE DEFAULT SYSDATE,
	CONSTRAINTS PK_CITIZEN PRIMARY KEY(ID)
);

CREATE SEQUENCE CITIZEN_ID_XXXX
MINVALUE 100
START WITH 100
INCREMENT BY 1
CACHE 20;

CREATE OR REPLACE FUNCTION GEN_ID(DOB IN DATE, DV_ IN VARCHAR2(2), ID OUT VARCHAR2(20))
	RETURN VARCHAR2
		IS
		DOB_CHAR VARCHAR2(10) := TO_CHAR(DOB, 'YYYYMMDD');
		SEQ_XXX NUMBER := CITIZEN_ID_XXXX.NEXTVAL;
BEGIN
	
	ID := CONCAT(DV_, DOB_CHAR);
	
	ID := CONCAT(ID, '.');
	
	ID := CONCAT(ID, SEQ_XXX);
	
	RETURN ID;
	
END;
/

CREATE TRIGGER TRG_CITIZEN
AFTER INSERT ON CITIZEN
FOR EACH ROW

DECLARE
	DV_ VARCHAR2(2) := :NEW.DV;
	DOB DATE := :NEW.DateOfBirth;
BEGIN
	IF(NEW.ID = NULL)
		THEN :NEW.ID = GEN_ID(DOB,DV_);
END;
/	