

	CREATE TABLE CUSTOMERS(
		CUSTOMER_ID NUMBER,
		CUSTOMER_NAME VARCHAR2(20),
		DoB DATE,
		CONSTRAINTS PK_CUSTOMER PRIMARY KEY(CUSTOMER_ID)
	);

	CREATE TABLE ADDRESS(
		A_ID NUMBER,
		DIVISION VARCHAR2(10),
		DISTRICT VARCHAR2(10),
		CUSTOMER_ID NUMBER,
		CONSTRAINTS PK_ADDRESS PRIMARY KEY(A_ID),
		CONSTRAINTS FK_CUSTOMER_ADDRESS FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
	);
	
	CREATE TABLE SUBSCRIPTION_INFO(
		SUBSCRIBER_TYPE VARCHAR2(10),
		SUBSCRIBER_LEVEL VARCHAR2(10),
		LIFETIME_USAGE NUMBER,
		CUSTOMER_ID NUMBER,
		CONSTRAINTS FK_SUBSCRIBER_ADDRESS FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
		CONSTRAINTS CHECK_TYPE CHECK(SUBSCRIBER_LEVEL IN('POSTPAID','PREPAID')),
		CONSTRAINTS CHECK_LEVEL CHECK(SUBSCRIBER_TYPE IN('BRONZE','SILVER','PLATINUM'))
	);
	
	
	CREATE SEQUENCE SEQ_CUSTOMER
	MINVALUE 101
	START WITH 101
	INCREMENT BY 1
	CACHE 10;
	
	INSERT INTO CUSTOMERS(CUSTOMER_ID, CUSTOMER_NAME, DoB) VALUES(SEQ_CUSTOMER.NEXTVAL,'AMADOU',TO_DATE('30/04/1989','DD/MM/YYYY'));
	INSERT INTO CUSTOMERS(CUSTOMER_ID, CUSTOMER_NAME, DoB) VALUES(SEQ_CUSTOMER.NEXTVAL,'ALY',TO_DATE('10/02/1994','DD/MM/YYYY'));
	INSERT INTO CUSTOMERS(CUSTOMER_ID, CUSTOMER_NAME, DoB) VALUES(SEQ_CUSTOMER.NEXTVAL,'AROUNA',TO_DATE('20/04/1991','DD/MM/YYYY'));
	INSERT INTO CUSTOMERS(CUSTOMER_ID, CUSTOMER_NAME, DoB) VALUES(SEQ_CUSTOMER.NEXTVAL,'MOUNIR',TO_DATE('15/12/1992','DD/MM/YYYY'));
	INSERT INTO CUSTOMERS(CUSTOMER_ID, CUSTOMER_NAME, DoB) VALUES(SEQ_CUSTOMER.NEXTVAL,'KALID',TO_DATE('19/01/1995','DD/MM/YYYY'));
	INSERT INTO CUSTOMERS(CUSTOMER_ID, CUSTOMER_NAME, DoB) VALUES(SEQ_CUSTOMER.NEXTVAL,'KARIM',TO_DATE('01/04/1993','DD/MM/YYYY'));
	
	CREATE SEQUENCE SEQ_ADDRESS
	MINVALUE 1
	START WITH 1
	INCREMENT BY 1
	CACHE 10;
	
	
	
	INSERT INTO ADDRESS(A_ID, DIVISION, DISTRICT, CUSTOMER_ID) VALUES(SEQ_ADDRESS.NEXTVAL, 'DHAKA', 'GAZIPUR', 101);
	INSERT INTO ADDRESS(A_ID, DIVISION, DISTRICT, CUSTOMER_ID) VALUES(SEQ_ADDRESS.NEXTVAL, 'DHAKA', 'SAVAR', 102);
	INSERT INTO ADDRESS(A_ID, DIVISION, DISTRICT, CUSTOMER_ID) VALUES(SEQ_ADDRESS.NEXTVAL, 'DHAKA', 'MIRPUR', 103);
	INSERT INTO ADDRESS(A_ID, DIVISION, DISTRICT, CUSTOMER_ID) VALUES(SEQ_ADDRESS.NEXTVAL, 'DHAKA', 'ARGAGAON', 104);
	INSERT INTO ADDRESS(A_ID, DIVISION, DISTRICT, CUSTOMER_ID) VALUES(SEQ_ADDRESS.NEXTVAL, 'DHAKA', 'GAZIPUR', 105);
	INSERT INTO ADDRESS(A_ID, DIVISION, DISTRICT, CUSTOMER_ID) VALUES(SEQ_ADDRESS.NEXTVAL, 'DHAKA', 'GAZIPUR', 106);
	
	
	INSERT INTO SUBSCRIPTION_INFO(CUSTOMER_ID, SUBSCRIBER_LEVEL, SUBSCRIBER_TYPE, LIFETIME_USAGE) VALUES(101, 'PREPAID', 'PLATINUM', 30000);
	INSERT INTO SUBSCRIPTION_INFO(CUSTOMER_ID, SUBSCRIBER_LEVEL, SUBSCRIBER_TYPE, LIFETIME_USAGE) VALUES(103, 'PREPAID', 'BRONZE', 5000);
	INSERT INTO SUBSCRIPTION_INFO(CUSTOMER_ID, SUBSCRIBER_LEVEL, SUBSCRIBER_TYPE, LIFETIME_USAGE) VALUES(104, 'POSTPAID', 'SILVER', 40000);
	INSERT INTO SUBSCRIPTION_INFO(CUSTOMER_ID, SUBSCRIBER_LEVEL, SUBSCRIBER_TYPE, LIFETIME_USAGE) VALUES(105, 'POSTPAID', 'PLATINUM',8000);
	INSERT INTO SUBSCRIPTION_INFO(CUSTOMER_ID, SUBSCRIBER_LEVEL, SUBSCRIBER_TYPE, LIFETIME_USAGE) VALUES(102, 'POSTPAID', 'BRONZE',13000);


	
	SELECT C.CUSTOMER_NAME, C.CUSTOMER_ID, S.LIFETIME_USAGE FROM CUSTOMERS C, SUBSCRIPTION_INFO S
		WHERE C.CUSTOMER_ID = S.CUSTOMER_ID AND S.LIFETIME_USAGE <= (SELECT MAX(LIFETIME_USAGE) FROM SUBSCRIPTION_INFO) AND ROWNUM <=5;
		
	
	SELECT C.CUSTOMER_NAME, C.DoB, A.DISTRICT, A.DIVISION FROM CUSTOMERS C, ADDRESS A, SUBSCRIPTION_INFO S
		WHERE C.CUSTOMER_ID = S.CUSTOMER_ID AND C.CUSTOMER_ID = A.CUSTOMER_ID AND S.LIFETIME_USAGE <= (SELECT AVG(LIFETIME_USAGE) FROM SUBSCRIPTION_INFO WHERE SUBSCRIBER_LEVEL='PREPAID' AND SUBSCRIBER_TYPE='SILVER');
		